version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: ghcr.io/joeferner/redis-commander:latest
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - "8081:8081"
      user: redis

volumes:
  redis-data: